services:
  postgres:
    image: postgres:16
    container_name: repiensa-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: repensatech
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  mongodb:
    image: mongo:8
    container_name: repensa-mongo
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

  backend:
    image: esteban003/repiensa-backend:latest
    container_name: repiensa-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://mongodb:27017/repensatech
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/repensatech
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
    depends_on:
      - postgres
      - mongodb
    restart: on-failure

  frontend:
    image: esteban003/repiensa-frontend:latest
    container_name: repiensa-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  mongo_data: 