sonar.projectKey=repiensa-tech
sonar.projectName=Repiensa Tech
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/prisma/migrations/**,**/cypress/**,**/k6/**,**/*.d.ts
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.coverage.exclusions=**/*.test.ts,**/*.spec.ts,**/tests/**,**/prisma/**,**/scripts/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
